name: pieces_ai
description: Ai动漫视频生成
version: 1.0.0+1
author: piecesAi
homepage: https://www.pencil-stub.com/#/


environment:
  sdk: ">=3.0.0 <4.0.0"

fluwx:
  app_id: 'wx27ea737e4e026bab'
  debug_logging: true # Logging in debug mode.
  android:
  #    no_pay: false # Set to false to disable payment.
  #    interrupt_wx_request: true # Defaults to true.
  #    flutter_activity: 'MainActivity' # Defaults to app's launcher
  ios:
    #    universal_link: https://testdomain.com
    #    scene_delegate: true # Defaults to false.
    no_pay: false # Set to false to disable payment.
#    ignore_security: true # Set to true to disable security seetings.


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.4
  cached_network_image: ^3.3.0 #网络图片缓存

  flutter_bloc: ^8.1.6 # 状态管理
  #  equatable: ^2.0.5 # 相等辅助
  #  stream_transform: ^2.1.0

  archive: ^3.6.1 # 解压
  package_info_plus: ^8.0.2 # 应用包信息
  webview_flutter: ^4.8.0
  go_router: ^14.2.3
  sqflite: ^2.3.3+1 # 数据库
  sqflite_common_ffi: ^2.3.3 # 数据库
  shared_preferences: ^2.3.2 # xml 固化
  path_provider: ^2.1.5  # 路径

  dio: ^5.4.0 # 网络请求
  #  jwt_decoder: ^2.0.1 # jwt 解析token是否过期
  #  connectivity_plus: ^5.0.2

  #  refresh: ^1.0.1
  #  toggle_rotate: ^1.0.1
  #  flutter_star: ^1.2.0 # 星星组件
  dash_painter: ^1.0.2
  wrapper: ^1.0.2
  yaml_modify: ^1.0.1

  url_launcher: ^6.3.0 # url
  share_plus: ^10.0.0 # 文字分享

  flutter_svg: ^2.0.7
  intl: ^0.19.0
  platform: ^3.1.0
  image: ^4.0.17
  flutter_spinkit: ^5.2.0 # loading
  flutter_markdown: ^0.6.4 # markdown
  #  file_selector: ^0.9.2+2
  file_picker: ^8.0.7
  #加密相关
  crypto: ^3.0.5
  image_compare_2: ^1.1.7
  # 轮播banner
  carousel_slider: ^5.0.0
  # 土司
  motion_toast: ^2.8.0
  # 首页拖拽按钮
  draggable_widget: ^2.0.0
  json_annotation: ^4.9.0
  #  media_kit: ^1.1.10                             # Primary package.
  #  media_kit_video: ^1.2.4
  #  media_kit_libs_video: ^1.0.4
  #  media_kit_libs_audio: ^1.0.4
  #  video_player_win: ^2.0.0
  video_player: ^2.9.2
  chewie: ^1.8.5
  just_audio: ^0.9.42

  # 生成二维码
  pretty_qr_code: ^3.3.0
  #图片切割小组件
  crop_your_image: ^1.0.2
  #各种样式的弹出Menu
  #  star_menu: ^4.0.1
  horizontal_list_view: ^1.1.0
  # 动画框架
  #  flutter_animate: ^4.5.0
  simple_animations: ^5.0.2
  # 设备信息
  device_info_plus: ^10.1.0
  #GIF控制加载
  gif: ^2.3.0
  #laoding框全局单例
  flutter_easyloading: ^3.0.5
  #全局配置文件
  global_configuration: ^2.0.0
  process_run: ^1.1.0
  # Android风格日志
  logger: ^2.3.0
  # 图像编辑器
  pro_image_editor: ^5.3.0
#  aj_image_editor: ^0.0.12
  # ffmpeg
  ffmpeg_kit_flutter_full_gpl: 6.0.3-LTS
  #  fluttertoast:
  #    git:
  #      url: https://github.com/ponnamkarthik/FlutterToast.git
  progress_border: ^0.1.5
  # 图片选择器+图片保存到相册
  image_gallery_saver_plus: ^3.0.5
  # github地址：https://github.com/FlutterStudioIst/image_gallery_saver.git 通过git地址引用
  #  image_gallery_saver:
  #    git:
  #      url: https://github.com/FlutterStudioIst/image_gallery_saver.git
  #      ref: master
  image_pickers: ^2.0.5+2
  wakelock_plus: ^1.2.8

  # 应用内支付
  in_app_purchase: ^3.2.0
#  video_editor: ^3.0.0
  fraction: ^4.1.4
  image_picker: ^0.8.9

  # ios14权限
  app_tracking_transparency: ^2.0.6

  # 三方widget 使用
  bottom_navy_bar: ^6.1.0
  textfield_tags: ^3.0.1
  buttons_tabbar: ^1.3.13

  # 本地化
  easy_localization: ^3.0.7

  # 友盟
#  umeng_common_sdk: ^1.2.3

  widget_repository:
    path: packages/widget_repository
  utils:
    path: packages/utils
  storage:
    path: packages/storage
  widgets:
    path: packages/widgets
  authentication:
    path: packages/authentication
  app:
    path: packages/app
  app_update:
    path: packages/app_update
  components:
    path: packages/components
  widget_module:
    path: packages/widget_module

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
    - assets/cfg/
    - assets/audio/
    - assets/images/head_icon/
    - assets/images/logo/
    - assets/images/widgets/
    - assets/flutter.db
    - assets/version.json
    - assets/translations/

  fonts: # 配置字体，可配置多个，支持ttf和otf,ttc等字体资源
    - family: TolyIconP
      fonts:
        - asset: assets/iconfont/toly_icon_p.ttf
    - family: TolyIcon
      fonts:
        - asset: assets/iconfont/toly_icon.ttf
    - family: IndieFlower #字体名
      fonts:
        - asset: assets/fonts/IndieFlower-Regular.ttf
    - family: BalooBhai2 #字体名
      fonts:
        - asset: assets/fonts/BalooBhai2-Regular.ttf
    - family: Inconsolata #字体名
      fonts:
        - asset: assets/fonts/Inconsolata-Regular.ttf
    - family: Neucha #字体名
      fonts:
        - asset: assets/fonts/Neucha-Regular.ttf
    - family: ComicNeue #字体名
      fonts:
        - asset: assets/fonts/ComicNeue-Regular.ttf
    - family: CHOPS
      fonts:
        - asset: assets/fonts/CHOPS.TTF
    - family: HanYiDaHei
      fonts:
        - asset: assets/fonts/hanyi.ttf












